### ISSUE TITLE
Installing user styles from different sources & Style metadata

### ISSUE THREAD

**Issue by dogancelik** [stylish-userstyles/stylish#165]
I see no documentation about this and I have few suggestions about it.
**I think this is a must-have feature for the freedom of users.**
#### A user should be able to install styles from other sources.

Example:
1. User goes to www.example.com
2. User clicks on the link (www.example.com/name_of_the_style.user.css)
3. Stylish detects the link by "**.user.css**" component
4. Stylish shows a dialog: "Would you like to add this site to allowed domains list?" 
└► This dialog is only shown **once** and shown when it is **required**
└► Domains can be removed/set/added from User Styles tab in about:addons
5. User clicks "Yes"
6. Stylish shows another dialog "Would you like to install this style?"
7. User clicks "Yes"
8. The style is installed.
#### Metadata is required to differentiate user styles

There should be two userstyle files. First one is **.user.css**, containing the style content and "==UserStyle==" block.

Second, **.meta.css** is a just a CSS file containing **only** "==UserStyle==" block. This file is used for version checking. Downloading this file will help the network and it will use less resources.

Example "==UserStyle" block (this should be placed at the beginning of a file)

```
/* ==UserStyle==
@name An example style
@namespace example.com
@description Bla bla
@updateURL http://example.com/example.meta.css
@downloadURL http://example.com/example.user.css
@version 1.0
==/UserStyle== */
```

I should be able to install any style by simply linking to it from **any site**.
(A user can install a style from [a.com]() when browsing [b.com]())
Greasemonkey install dialog is a good example for this.

[http://forum.userstyles.org/discussion/comment/9774](This) is a related thread about it from 4 years ago.

**Comment by noscript** [comment]
Sad to see this closed. I prefer to keep my scripts and styles on gist.github.com. While it works perfectly for Greasemonkey scripts, some extra clicks are required for styles.

> I would consider a change that made it easier for sites to get into extensions.stylish.install.allowedDomains

If this would require some changes done on GitHub side for example, I do not think it's possible.

**Comment by Fironet** [comment]
Just commenting to add there doesn't seem to be a way to add stylesheets from sources other than userstyles.org for Stylish on the Android version of Firefox (at least with the user.css I've tried hosted on Github), nor is adding them manually possible with that version of the addon, so this suggestion to include a pop-up notification would be very much appreciated in that case.

Edit: I should also mention that there is no Manage or 'Install from URL' option in the Stylish version on FF for Android for me (using the latest version), only *Disable* and *Uninstall*. So per the workarounds @JasonBarnabe listed the only one that would apparently work here is creating a compatible web page with the appropriate Javascript and adding the page to the about:config whitelist.
