### ISSUE TITLE
Can you add an option to turn off auto-indentation when editing?

### ISSUE THREAD

**Issue by DavidJCobb** [stylish-userstyles/stylish#180]
When editing a userstyle, I find that Stylish's relatively-new text editor automatically indents when inserting a line break. When you finish typing a CSS rule (closing brace inserted), it will also modify the whitespace on the current line to match what it thinks is proper indentation.

It's all meant to be helpful, but it's actually really, really annoying if your personal preferences don't happen to line up with what Stylish considers to be correct. Any chance we can get an option or a pref to control this behavior?

**Comment by Gitoffthelawn** [comment]
Setting `devtools.editor.tabsize` set to `0` does not seem to disable auto-indentation in the editor in Firefox 47.0.1.

Is there a way to turn it off in current versions of Firefox?
