### ISSUE TITLE
[PaleMoon] No syntax highlight and auto-complete in edit tab.

### ISSUE THREAD

**Issue by BladeMight** [stylish-userstyles/stylish#278]
I recently switched to Pale Moon and have noticed that Stylish(my favorite add-on) don't have syntax highlight and auto-complete in editing, why?

**Comment by BladeMight** [comment]
Latest too...

**Comment by BladeMight** [comment]
Maybe you could add at least feature to select external editor?

**Comment by JasonBarnabe** [comment]
Most likely because Pale Moon is based on an older version of Firefox that does not support the built-in editor Stylish currently is trying to use.

**Comment by BladeMight** [comment]
@JasonBarnabe then can i select external like Notepad++?

**Comment by JasonBarnabe** [comment]
You should still be able to use [It's All Text](https://addons.mozilla.org/en-US/firefox/addon/its-all-text/).

**Comment by BladeMight** [comment]
No, it doesn't works for me :/

**Comment by ghost** [comment]
Looks like it fixed in latest version.
