### ISSUE TITLE
Suggestion: Bring this extension to edge

### ISSUE THREAD

**Issue by lychichem** [stylish-userstyles/stylish#284]
As MS introduced its [Microsoft Edge Extension Toolkit](https://www.microsoft.com/zh-cn/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb?tduid=$c9c69b2d21266c6acf6b0f83f81e62b2$$235166$$2397989$$$$$&reportthisapp=1), are you interested in bring this extension to MS Edge?

**Comment by yfdyh000** [comment]
For https://github.com/JasonBarnabe/stylish-chrome.
I get no response on options page always, after convert.
