### ISSUE TITLE
about:blank page styling stopped working

### ISSUE THREAD

**Issue by LaserMoai** [stylish-userstyles/stylish#308]
It stopped working recently on both stable and developer Firefox versions for some reason. I've tried several dark themes.

OS: Arch Linux

**Comment by DanaMW** [comment]
I have it installed on Arch on FF 53 X64 development and google Chrome dev and it works as expected. Just to let you know.

**Comment by LaserMoai** [comment]
What's even more strange, it looks fine when I just open it, but the web pages flash white when being loaded.

**Comment by LaserMoai** [comment]
Probably a Firefox issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1335026
