### ISSUE TITLE
Jason, please consider to archive the repos

### ISSUE THREAD

**Issue by cyfung1031** [stylish-userstyles/stylish#344]
@JasonBarnabe 

Since there is no longer any active development, I think you should archive these repos.

<img width="911" alt="Screen Shot 2023-09-22 at 12 09 55" src="https://github.com/stylish-userstyles/stylish/assets/44498510/9cc8bbe9-5b3f-4f77-9ee4-9f520b409f0b">

## Public archive
As [an example](https://github.com/inotia00/VancedMicroG), 
<img width="619" alt="Screen Shot 2023-09-22 at 12 11 41" src="https://github.com/stylish-userstyles/stylish/assets/44498510/ba2e575d-caae-450e-93ee-2b906c196be1">

Then no further issues will be able to open and it is a clear indicator to the users that these are no longer maintained or developed.

**Comment by JasonBarnabe** [comment]
I am not in control of this repo.
