### ISSUE TITLE
Sync styles on Chrome

### ISSUE THREAD

**Issue by JasonBarnabe** [stylish-userstyles/stylish#94]
http://forum.userstyles.org/discussion/33477/sync-userstyles-between-chrome-instances#Item_4

**Comment by janaspage** [comment]
May I ask why this was closed? Has the issue been resolved, or is it unresolvable? Thank you.

**Comment by PxlBuzzard** [comment]
[This issue](https://github.com/JasonBarnabe/stylish-chrome/issues/2) for stylish-chrome seems to have gained more traction.

**Comment by JasonBarnabe** [comment]
Yes, this is the repo for Stylish for _Firefox_.

**Comment by janaspage** [comment]
Thank you.
